export const CONFIGURATOR_PAGE_CONSTANTS = {
    CONFIGURATOR_PAGE_TITLE: 'Polestar 4 - Designa din bil i konfiguratorn | Polestar Sverige',
    CONFIGURATOR_PAGE_LOAD_TIMEOUT: 30000,
    CONFIGURATION_UI_UPDATE_TIMEOUT: 2000
};